-- For Episode IV
CREATE TABLE episodeIV (name STRING, line STRING) 
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' TBLPROPERTIES ("skip.header.line.count"="2");

-- Load episodeIV text file into the table
LOAD DATA LOCAL INPATH '/root/episodes/episodeIV_dialogues.txt' INTO TABLE episodeIV;

-- Generate output and export it
INSERT OVERWRITE LOCAL DIRECTORY '/root/results' ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
SELECT COUNT(*) FROM episodeIV WHERE INSTR(line, 'Luke')>0;






